# docker compose for local testing
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    # command: uwsgi --ini shareable/wsgi/uwsgi.ini
    # command: python manage.py runserver 0.0.0.0:8000
    restart: always
    env_file: .env
    networks:
      - django-backend-tier
    volumes:
      - ./:/softpage_note_api
    depends_on:
      - db
      - redis
    ports:
    - 8000:8000

  db:
    image: postgres:15.1-alpine
    restart: unless-stopped
    networks:
      - django-backend-tier
    volumes:
      - backstage-db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dev
    ports:
      - 5432:5432

  redis:
    image: redis:6
    restart: unless-stopped
    networks:
      - django-backend-tier
    volumes:
      - backstage-redis:/data

volumes:
  backstage-db:
    driver: local
  backstage-redis:
    driver: local

networks:
  django-backend-tier:
    driver: bridge
